name: first-app
on:
  push:
    paths:
      - "first-app/"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: build the assets
        run: yarn ci && yarn run build
