name: first-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working_directory: ./first-app
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: build the assets
        run: yarn run build
